#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  pactl set-sink-volume 0 +5%	
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  pactl set-sink-mute 0 toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  pactl set-sink-volume 0 -5%
fi

volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

echo "${volume}%"
echo "${volume}%"
echo ""
